version: '3.1'

services:

  web:
    container_name: logus-web-container
    build: .

    # Utilizando Gunicorn
    command: bash -c 'python manage.py collectstatic --noinput && gunicorn logusweb.wsgi -b 0.0.0.0:8000 -w 3' # Modo Producao (S/ Reload)
    #command: bash -c 'python manage.py collectstatic --noinput && gunicorn logusweb.wsgi -b 0.0.0.0:8000 -w 3 --reload' # Modo Desenvolvimento

    # Sem Gunicorn
    #command: bash -c 'python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 --insecure'
    
    volumes:
      - ./codigo:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  db:
    container_name: logus-db-container
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /dados
    volumes:
      - pg_data:/dados

volumes:
  pg_data:
