# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valortotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fone1', models.CharField(max_length=20, verbose_name='telefone 1')),
                ('fone2', models.CharField(max_length=20, verbose_name='telefone 2')),
                ('data_pub', models.DateField(auto_now_add=True, verbose_name='data do cadastro')),
                ('tipo', models.CharField(choices=[('F', 'F\xedsica'), ('J', 'Jur\xeddica')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItensEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('valoru', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor Unit\xe1rio')),
                ('valort', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Sub_Total')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logus.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='itensentrada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logus.Produto'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logus.Fornecedor'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='itens',
            field=models.ManyToManyField(through='logus.ItensEntrada', to='logus.Produto'),
        ),
    ]
