# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='geo',
            field=models.ManyToManyField(related_name='offers', to='logus.OfferGeo'),
        ),
    ]
