# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0003_auto_20171111_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
