# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0004_auto_20171111_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensentrada',
            name='valort',
        ),
    ]
