# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0005_remove_itensentrada_valort'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensentrada',
            name='_valort',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
