# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0011_auto_20171117_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensentrada',
            name='valort',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 21, 15, 29, 453888)),
        ),
    ]
