# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0012_auto_20171120_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 11, 20, 22, 14, 44, 909143)),
        ),
    ]
