# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0015_auto_20171204_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='itens',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 11, 21, 9, 279900)),
        ),
        migrations.AlterField(
            model_name='itensentrada',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_det', to='logus.Entrada'),
        ),
    ]
