# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0016_auto_20171204_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensentrada',
            name='valort',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 15, 41, 3, 903638)),
        ),
    ]
