# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0018_auto_20171206_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensentrada',
            name='valort',
        ),
        migrations.RemoveField(
            model_name='itensentrada',
            name='valoru',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 15, 7, 16, 392261)),
        ),
    ]
