# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0019_auto_20171206_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensentrada',
            name='valoru',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 15, 25, 10, 738772)),
        ),
    ]
