# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0021_auto_20171206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 19, 7, 5, 811715)),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valortotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor total'),
        ),
    ]
