# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0022_auto_20171207_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 19, 13, 8, 587902)),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
