# Generated by Django 2.0 on 2017-12-14 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0023_auto_20171207_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 12, 14, 16, 2, 43, 978380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valortotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logus.Profile'),
        ),
        migrations.AlterField(
            model_name='itensentrada',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
