# Generated by Django 2.0.1 on 2018-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0025_auto_20171226_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'permissions': (('permitir_adicionar_fornecedor', 'Permitir adicionar fornecedores'),), 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
    ]
