# Generated by Django 2.0.1 on 2018-03-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0027_auto_20180308_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'permissions': (('permitir_listar_fornecedor', 'Permitir listar fornecedores'), ('permitir_adicionar_fornecedor', 'Permitir adicionar fornecedores'), ('permitir_alterar_fornecedor', 'Permitir alterar fornecedores'), ('permitir_remover_fornecedor', 'Permitir remover fornecedores')), 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
    ]
