# Generated by Django 2.0.1 on 2018-03-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0031_auto_20180309_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
