# Generated by Django 2.0.1 on 2018-03-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0032_auto_20180309_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'permissions': (('list_entrada', 'Permitir listar entradas'),), 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao'], 'permissions': (('list_produto', 'Permitir listar produtos'),), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
