# Generated by Django 2.0.3 on 2018-03-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0033_auto_20180311_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='profile',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
